require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'RiveReactNativeExample' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  pod 'rive-react-native', :path => '../..'
  pod 'OpenSSL-Universal'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    # Issue with RCT-Folly and XCode 15 with recommended path forward explained
    # here: https://github.com/facebook/react-native/issues/39568#issuecomment-1762890606
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # This is a temporary workaround for the issue described here:
    # https://github.com/facebook/react-native/issues/43335. Flipper is no longer
    # used in React Native 0.74 so this workaround can be removed once we upgrade.
    installer.pods_project.targets.each do |target|
      if target.name == 'Flipper'
        file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
        contents = File.read(file_path)
        unless contents.include?('#include <functional>')
          File.chmod(0755, file_path)
          File.open(file_path, 'w') do |file|
            file.puts('#include <functional>')
            file.puts(contents)
          end
        end
      end
    end
  end
end
